[pytest]
testpaths = tests
addopts = --import-mode=importlib
pythonpath = src libraries/cem_common/src libraries/fem_adaptivity/src libraries/periodic_eigensolver/src solvers/fem/electrostatics/src solvers/fem/periodic_modes/src solvers/fem/waveguide_modes/src solvers/fem/waveguide_scattering/src
markers =
    gmsh: test requiring Gmsh
    slow: numerical convergence or performance test
